//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSoft.ControlHorarios.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Tipo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
